// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yywncszfyhfbeqzedxnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5d25jc3pmeWhmYmVxemVkeG5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzNzc1NDEsImV4cCI6MjA3NTk1MzU0MX0.pmzRuNh_tB8fltvAQHpqynHvkRLSaWMmJs8mzGhHO6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
